services:
  bdd-test:
    build:
      context: ./bdd-test
      dockerfile: Dockerfile
    depends_on:
      - idemax
      - redis
      - zookeeper
      - kafka
    command: >
      /bin/sh -c "
      dockerize -wait http://idemax:8080/health-check -timeout 30s \
      -wait tcp://redis:6379 -timeout 30s \
      -wait tcp://kafka:9092 -timeout 30s \
      && exec /app/execute_tests.sh"
